#!/usr/bin/env bash
# pings an ip address passed as an argument
if [ $# -eq 0 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address=$1

echo "Pinging $ip_address..."

for ((i=1; i<=5; i++))
do
  ping -c 1 $ip_address
done
